config system_bd_altera_emif_a10_hps_180_ebac5ai_cfg;
		design system_bd_altera_emif_a10_hps_180_ebac5ai;
		instance system_bd_altera_emif_a10_hps_180_ebac5ai.arch use system_bd_altera_emif_arch_nf_180.system_bd_altera_emif_arch_nf_180_ewuzaei;
endconfig

