// system_bd_altera_arria10_hps_180_sja5gji.v

// This file was auto-generated from altera_hps_arria10_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module system_bd_altera_arria10_hps_180_sja5gji #(
		parameter F2S_Width = 0,
		parameter S2F_Width = 0
	) (
		output wire          h2f_rst_n,                 //         h2f_reset.reset_n
		output wire          s2f_user0_clk,             //   h2f_user0_clock.clk
		input  wire [4095:0] emif_emif_to_hps,          //              emif.emif_to_hps
		output wire [4095:0] emif_hps_to_emif,          //                  .hps_to_emif
		input  wire          emif_emif_to_gp,           //                  .emif_to_gp
		output wire [1:0]    emif_gp_to_emif,           //                  .gp_to_emif
		input  wire          h2f_lw_axi_clk,            //  h2f_lw_axi_clock.clk
		input  wire          h2f_lw_axi_rst,            //  h2f_lw_axi_reset.reset_n
		output wire [3:0]    h2f_lw_AWID,               // h2f_lw_axi_master.awid
		output wire [20:0]   h2f_lw_AWADDR,             //                  .awaddr
		output wire [3:0]    h2f_lw_AWLEN,              //                  .awlen
		output wire [2:0]    h2f_lw_AWSIZE,             //                  .awsize
		output wire [1:0]    h2f_lw_AWBURST,            //                  .awburst
		output wire [1:0]    h2f_lw_AWLOCK,             //                  .awlock
		output wire [3:0]    h2f_lw_AWCACHE,            //                  .awcache
		output wire [2:0]    h2f_lw_AWPROT,             //                  .awprot
		output wire          h2f_lw_AWVALID,            //                  .awvalid
		input  wire          h2f_lw_AWREADY,            //                  .awready
		output wire [4:0]    h2f_lw_AWUSER,             //                  .awuser
		output wire [3:0]    h2f_lw_WID,                //                  .wid
		output wire [31:0]   h2f_lw_WDATA,              //                  .wdata
		output wire [3:0]    h2f_lw_WSTRB,              //                  .wstrb
		output wire          h2f_lw_WLAST,              //                  .wlast
		output wire          h2f_lw_WVALID,             //                  .wvalid
		input  wire          h2f_lw_WREADY,             //                  .wready
		input  wire [3:0]    h2f_lw_BID,                //                  .bid
		input  wire [1:0]    h2f_lw_BRESP,              //                  .bresp
		input  wire          h2f_lw_BVALID,             //                  .bvalid
		output wire          h2f_lw_BREADY,             //                  .bready
		output wire [3:0]    h2f_lw_ARID,               //                  .arid
		output wire [20:0]   h2f_lw_ARADDR,             //                  .araddr
		output wire [3:0]    h2f_lw_ARLEN,              //                  .arlen
		output wire [2:0]    h2f_lw_ARSIZE,             //                  .arsize
		output wire [1:0]    h2f_lw_ARBURST,            //                  .arburst
		output wire [1:0]    h2f_lw_ARLOCK,             //                  .arlock
		output wire [3:0]    h2f_lw_ARCACHE,            //                  .arcache
		output wire [2:0]    h2f_lw_ARPROT,             //                  .arprot
		output wire          h2f_lw_ARVALID,            //                  .arvalid
		input  wire          h2f_lw_ARREADY,            //                  .arready
		output wire [4:0]    h2f_lw_ARUSER,             //                  .aruser
		input  wire [3:0]    h2f_lw_RID,                //                  .rid
		input  wire [31:0]   h2f_lw_RDATA,              //                  .rdata
		input  wire [1:0]    h2f_lw_RRESP,              //                  .rresp
		input  wire          h2f_lw_RLAST,              //                  .rlast
		input  wire          h2f_lw_RVALID,             //                  .rvalid
		output wire          h2f_lw_RREADY,             //                  .rready
		input  wire [31:0]   f2h_irq_p0,                //          f2h_irq0.irq
		input  wire [31:0]   f2h_irq_p1,                //          f2h_irq1.irq
		output wire          hps_io_phery_emac1_TX_CLK, //            hps_io.hps_io_phery_emac1_TX_CLK
		output wire          hps_io_phery_emac1_TXD0,   //                  .hps_io_phery_emac1_TXD0
		output wire          hps_io_phery_emac1_TXD1,   //                  .hps_io_phery_emac1_TXD1
		output wire          hps_io_phery_emac1_TXD2,   //                  .hps_io_phery_emac1_TXD2
		output wire          hps_io_phery_emac1_TXD3,   //                  .hps_io_phery_emac1_TXD3
		input  wire          hps_io_phery_emac1_RX_CTL, //                  .hps_io_phery_emac1_RX_CTL
		output wire          hps_io_phery_emac1_TX_CTL, //                  .hps_io_phery_emac1_TX_CTL
		input  wire          hps_io_phery_emac1_RX_CLK, //                  .hps_io_phery_emac1_RX_CLK
		input  wire          hps_io_phery_emac1_RXD0,   //                  .hps_io_phery_emac1_RXD0
		input  wire          hps_io_phery_emac1_RXD1,   //                  .hps_io_phery_emac1_RXD1
		input  wire          hps_io_phery_emac1_RXD2,   //                  .hps_io_phery_emac1_RXD2
		input  wire          hps_io_phery_emac1_RXD3,   //                  .hps_io_phery_emac1_RXD3
		inout  wire          hps_io_phery_emac1_MDIO,   //                  .hps_io_phery_emac1_MDIO
		output wire          hps_io_phery_emac1_MDC,    //                  .hps_io_phery_emac1_MDC
		inout  wire          hps_io_phery_sdmmc_CMD,    //                  .hps_io_phery_sdmmc_CMD
		inout  wire          hps_io_phery_sdmmc_D0,     //                  .hps_io_phery_sdmmc_D0
		inout  wire          hps_io_phery_sdmmc_D1,     //                  .hps_io_phery_sdmmc_D1
		inout  wire          hps_io_phery_sdmmc_D2,     //                  .hps_io_phery_sdmmc_D2
		inout  wire          hps_io_phery_sdmmc_D3,     //                  .hps_io_phery_sdmmc_D3
		output wire          hps_io_phery_sdmmc_CCLK,   //                  .hps_io_phery_sdmmc_CCLK
		inout  wire          hps_io_phery_usb1_DATA0,   //                  .hps_io_phery_usb1_DATA0
		inout  wire          hps_io_phery_usb1_DATA1,   //                  .hps_io_phery_usb1_DATA1
		inout  wire          hps_io_phery_usb1_DATA2,   //                  .hps_io_phery_usb1_DATA2
		inout  wire          hps_io_phery_usb1_DATA3,   //                  .hps_io_phery_usb1_DATA3
		inout  wire          hps_io_phery_usb1_DATA4,   //                  .hps_io_phery_usb1_DATA4
		inout  wire          hps_io_phery_usb1_DATA5,   //                  .hps_io_phery_usb1_DATA5
		inout  wire          hps_io_phery_usb1_DATA6,   //                  .hps_io_phery_usb1_DATA6
		inout  wire          hps_io_phery_usb1_DATA7,   //                  .hps_io_phery_usb1_DATA7
		input  wire          hps_io_phery_usb1_CLK,     //                  .hps_io_phery_usb1_CLK
		output wire          hps_io_phery_usb1_STP,     //                  .hps_io_phery_usb1_STP
		input  wire          hps_io_phery_usb1_DIR,     //                  .hps_io_phery_usb1_DIR
		input  wire          hps_io_phery_usb1_NXT,     //                  .hps_io_phery_usb1_NXT
		input  wire          hps_io_phery_uart1_RX,     //                  .hps_io_phery_uart1_RX
		output wire          hps_io_phery_uart1_TX,     //                  .hps_io_phery_uart1_TX
		inout  wire          hps_io_phery_i2c1_SDA,     //                  .hps_io_phery_i2c1_SDA
		inout  wire          hps_io_phery_i2c1_SCL,     //                  .hps_io_phery_i2c1_SCL
		inout  wire          hps_io_gpio_gpio0_io1,     //                  .hps_io_gpio_gpio0_io1
		inout  wire          hps_io_gpio_gpio0_io9      //                  .hps_io_gpio_gpio0_io9
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (F2S_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f2s_width_check ( .error(1'b1) );
		end
		if (S2F_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s2f_width_check ( .error(1'b1) );
		end
	endgenerate

	system_bd_altera_arria10_interface_generator_140_zb7v6oi fpga_interfaces (
		.h2f_rst_n        (h2f_rst_n),        //         h2f_reset.reset_n
		.s2f_user0_clk    (s2f_user0_clk),    //   h2f_user0_clock.clk
		.emif_emif_to_hps (emif_emif_to_hps), //              emif.emif_to_hps
		.emif_hps_to_emif (emif_hps_to_emif), //                  .hps_to_emif
		.emif_emif_to_gp  (emif_emif_to_gp),  //                  .emif_to_gp
		.emif_gp_to_emif  (emif_gp_to_emif),  //                  .gp_to_emif
		.h2f_lw_axi_clk   (h2f_lw_axi_clk),   //  h2f_lw_axi_clock.clk
		.h2f_lw_axi_rst   (h2f_lw_axi_rst),   //  h2f_lw_axi_reset.reset_n
		.h2f_lw_AWID      (h2f_lw_AWID),      // h2f_lw_axi_master.awid
		.h2f_lw_AWADDR    (h2f_lw_AWADDR),    //                  .awaddr
		.h2f_lw_AWLEN     (h2f_lw_AWLEN),     //                  .awlen
		.h2f_lw_AWSIZE    (h2f_lw_AWSIZE),    //                  .awsize
		.h2f_lw_AWBURST   (h2f_lw_AWBURST),   //                  .awburst
		.h2f_lw_AWLOCK    (h2f_lw_AWLOCK),    //                  .awlock
		.h2f_lw_AWCACHE   (h2f_lw_AWCACHE),   //                  .awcache
		.h2f_lw_AWPROT    (h2f_lw_AWPROT),    //                  .awprot
		.h2f_lw_AWVALID   (h2f_lw_AWVALID),   //                  .awvalid
		.h2f_lw_AWREADY   (h2f_lw_AWREADY),   //                  .awready
		.h2f_lw_AWUSER    (h2f_lw_AWUSER),    //                  .awuser
		.h2f_lw_WID       (h2f_lw_WID),       //                  .wid
		.h2f_lw_WDATA     (h2f_lw_WDATA),     //                  .wdata
		.h2f_lw_WSTRB     (h2f_lw_WSTRB),     //                  .wstrb
		.h2f_lw_WLAST     (h2f_lw_WLAST),     //                  .wlast
		.h2f_lw_WVALID    (h2f_lw_WVALID),    //                  .wvalid
		.h2f_lw_WREADY    (h2f_lw_WREADY),    //                  .wready
		.h2f_lw_BID       (h2f_lw_BID),       //                  .bid
		.h2f_lw_BRESP     (h2f_lw_BRESP),     //                  .bresp
		.h2f_lw_BVALID    (h2f_lw_BVALID),    //                  .bvalid
		.h2f_lw_BREADY    (h2f_lw_BREADY),    //                  .bready
		.h2f_lw_ARID      (h2f_lw_ARID),      //                  .arid
		.h2f_lw_ARADDR    (h2f_lw_ARADDR),    //                  .araddr
		.h2f_lw_ARLEN     (h2f_lw_ARLEN),     //                  .arlen
		.h2f_lw_ARSIZE    (h2f_lw_ARSIZE),    //                  .arsize
		.h2f_lw_ARBURST   (h2f_lw_ARBURST),   //                  .arburst
		.h2f_lw_ARLOCK    (h2f_lw_ARLOCK),    //                  .arlock
		.h2f_lw_ARCACHE   (h2f_lw_ARCACHE),   //                  .arcache
		.h2f_lw_ARPROT    (h2f_lw_ARPROT),    //                  .arprot
		.h2f_lw_ARVALID   (h2f_lw_ARVALID),   //                  .arvalid
		.h2f_lw_ARREADY   (h2f_lw_ARREADY),   //                  .arready
		.h2f_lw_ARUSER    (h2f_lw_ARUSER),    //                  .aruser
		.h2f_lw_RID       (h2f_lw_RID),       //                  .rid
		.h2f_lw_RDATA     (h2f_lw_RDATA),     //                  .rdata
		.h2f_lw_RRESP     (h2f_lw_RRESP),     //                  .rresp
		.h2f_lw_RLAST     (h2f_lw_RLAST),     //                  .rlast
		.h2f_lw_RVALID    (h2f_lw_RVALID),    //                  .rvalid
		.h2f_lw_RREADY    (h2f_lw_RREADY),    //                  .rready
		.f2h_irq_p0       (f2h_irq_p0),       //          f2h_irq0.irq
		.f2h_irq_p1       (f2h_irq_p1)        //          f2h_irq1.irq
	);

	system_bd_altera_arria10_hps_io_180_jn2c66q hps_io (
		.hps_io_phery_emac1_TX_CLK (hps_io_phery_emac1_TX_CLK), // hps_io.hps_io_phery_emac1_TX_CLK
		.hps_io_phery_emac1_TXD0   (hps_io_phery_emac1_TXD0),   //       .hps_io_phery_emac1_TXD0
		.hps_io_phery_emac1_TXD1   (hps_io_phery_emac1_TXD1),   //       .hps_io_phery_emac1_TXD1
		.hps_io_phery_emac1_TXD2   (hps_io_phery_emac1_TXD2),   //       .hps_io_phery_emac1_TXD2
		.hps_io_phery_emac1_TXD3   (hps_io_phery_emac1_TXD3),   //       .hps_io_phery_emac1_TXD3
		.hps_io_phery_emac1_RX_CTL (hps_io_phery_emac1_RX_CTL), //       .hps_io_phery_emac1_RX_CTL
		.hps_io_phery_emac1_TX_CTL (hps_io_phery_emac1_TX_CTL), //       .hps_io_phery_emac1_TX_CTL
		.hps_io_phery_emac1_RX_CLK (hps_io_phery_emac1_RX_CLK), //       .hps_io_phery_emac1_RX_CLK
		.hps_io_phery_emac1_RXD0   (hps_io_phery_emac1_RXD0),   //       .hps_io_phery_emac1_RXD0
		.hps_io_phery_emac1_RXD1   (hps_io_phery_emac1_RXD1),   //       .hps_io_phery_emac1_RXD1
		.hps_io_phery_emac1_RXD2   (hps_io_phery_emac1_RXD2),   //       .hps_io_phery_emac1_RXD2
		.hps_io_phery_emac1_RXD3   (hps_io_phery_emac1_RXD3),   //       .hps_io_phery_emac1_RXD3
		.hps_io_phery_emac1_MDIO   (hps_io_phery_emac1_MDIO),   //       .hps_io_phery_emac1_MDIO
		.hps_io_phery_emac1_MDC    (hps_io_phery_emac1_MDC),    //       .hps_io_phery_emac1_MDC
		.hps_io_phery_sdmmc_CMD    (hps_io_phery_sdmmc_CMD),    //       .hps_io_phery_sdmmc_CMD
		.hps_io_phery_sdmmc_D0     (hps_io_phery_sdmmc_D0),     //       .hps_io_phery_sdmmc_D0
		.hps_io_phery_sdmmc_D1     (hps_io_phery_sdmmc_D1),     //       .hps_io_phery_sdmmc_D1
		.hps_io_phery_sdmmc_D2     (hps_io_phery_sdmmc_D2),     //       .hps_io_phery_sdmmc_D2
		.hps_io_phery_sdmmc_D3     (hps_io_phery_sdmmc_D3),     //       .hps_io_phery_sdmmc_D3
		.hps_io_phery_sdmmc_CCLK   (hps_io_phery_sdmmc_CCLK),   //       .hps_io_phery_sdmmc_CCLK
		.hps_io_phery_usb1_DATA0   (hps_io_phery_usb1_DATA0),   //       .hps_io_phery_usb1_DATA0
		.hps_io_phery_usb1_DATA1   (hps_io_phery_usb1_DATA1),   //       .hps_io_phery_usb1_DATA1
		.hps_io_phery_usb1_DATA2   (hps_io_phery_usb1_DATA2),   //       .hps_io_phery_usb1_DATA2
		.hps_io_phery_usb1_DATA3   (hps_io_phery_usb1_DATA3),   //       .hps_io_phery_usb1_DATA3
		.hps_io_phery_usb1_DATA4   (hps_io_phery_usb1_DATA4),   //       .hps_io_phery_usb1_DATA4
		.hps_io_phery_usb1_DATA5   (hps_io_phery_usb1_DATA5),   //       .hps_io_phery_usb1_DATA5
		.hps_io_phery_usb1_DATA6   (hps_io_phery_usb1_DATA6),   //       .hps_io_phery_usb1_DATA6
		.hps_io_phery_usb1_DATA7   (hps_io_phery_usb1_DATA7),   //       .hps_io_phery_usb1_DATA7
		.hps_io_phery_usb1_CLK     (hps_io_phery_usb1_CLK),     //       .hps_io_phery_usb1_CLK
		.hps_io_phery_usb1_STP     (hps_io_phery_usb1_STP),     //       .hps_io_phery_usb1_STP
		.hps_io_phery_usb1_DIR     (hps_io_phery_usb1_DIR),     //       .hps_io_phery_usb1_DIR
		.hps_io_phery_usb1_NXT     (hps_io_phery_usb1_NXT),     //       .hps_io_phery_usb1_NXT
		.hps_io_phery_uart1_RX     (hps_io_phery_uart1_RX),     //       .hps_io_phery_uart1_RX
		.hps_io_phery_uart1_TX     (hps_io_phery_uart1_TX),     //       .hps_io_phery_uart1_TX
		.hps_io_phery_i2c1_SDA     (hps_io_phery_i2c1_SDA),     //       .hps_io_phery_i2c1_SDA
		.hps_io_phery_i2c1_SCL     (hps_io_phery_i2c1_SCL),     //       .hps_io_phery_i2c1_SCL
		.hps_io_gpio_gpio0_io1     (hps_io_gpio_gpio0_io1),     //       .hps_io_gpio_gpio0_io1
		.hps_io_gpio_gpio0_io9     (hps_io_gpio_gpio0_io9)      //       .hps_io_gpio_gpio0_io9
	);

endmodule
