// system_bd.v

// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module system_bd (
		input  wire        sys_clk_clk,                          //             sys_clk.clk
		output wire [0:0]  sys_hps_ddr_mem_ck,                   //         sys_hps_ddr.mem_ck
		output wire [0:0]  sys_hps_ddr_mem_ck_n,                 //                    .mem_ck_n
		output wire [16:0] sys_hps_ddr_mem_a,                    //                    .mem_a
		output wire [0:0]  sys_hps_ddr_mem_act_n,                //                    .mem_act_n
		output wire [1:0]  sys_hps_ddr_mem_ba,                   //                    .mem_ba
		output wire [1:0]  sys_hps_ddr_mem_bg,                   //                    .mem_bg
		output wire [0:0]  sys_hps_ddr_mem_cke,                  //                    .mem_cke
		output wire [0:0]  sys_hps_ddr_mem_cs_n,                 //                    .mem_cs_n
		output wire [0:0]  sys_hps_ddr_mem_odt,                  //                    .mem_odt
		output wire [0:0]  sys_hps_ddr_mem_reset_n,              //                    .mem_reset_n
		output wire [0:0]  sys_hps_ddr_mem_par,                  //                    .mem_par
		input  wire [0:0]  sys_hps_ddr_mem_alert_n,              //                    .mem_alert_n
		inout  wire [3:0]  sys_hps_ddr_mem_dqs,                  //                    .mem_dqs
		inout  wire [3:0]  sys_hps_ddr_mem_dqs_n,                //                    .mem_dqs_n
		inout  wire [31:0] sys_hps_ddr_mem_dq,                   //                    .mem_dq
		inout  wire [3:0]  sys_hps_ddr_mem_dbi_n,                //                    .mem_dbi_n
		input  wire        sys_hps_ddr_oct_oct_rzqin,            //     sys_hps_ddr_oct.oct_rzqin
		input  wire        sys_hps_ddr_ref_clk_clk,              // sys_hps_ddr_ref_clk.clk
		input  wire        sys_hps_ddr_rstn_reset_n,             //    sys_hps_ddr_rstn.reset_n
		output wire        sys_hps_io_hps_io_phery_emac1_TX_CLK, //          sys_hps_io.hps_io_phery_emac1_TX_CLK
		output wire        sys_hps_io_hps_io_phery_emac1_TXD0,   //                    .hps_io_phery_emac1_TXD0
		output wire        sys_hps_io_hps_io_phery_emac1_TXD1,   //                    .hps_io_phery_emac1_TXD1
		output wire        sys_hps_io_hps_io_phery_emac1_TXD2,   //                    .hps_io_phery_emac1_TXD2
		output wire        sys_hps_io_hps_io_phery_emac1_TXD3,   //                    .hps_io_phery_emac1_TXD3
		input  wire        sys_hps_io_hps_io_phery_emac1_RX_CTL, //                    .hps_io_phery_emac1_RX_CTL
		output wire        sys_hps_io_hps_io_phery_emac1_TX_CTL, //                    .hps_io_phery_emac1_TX_CTL
		input  wire        sys_hps_io_hps_io_phery_emac1_RX_CLK, //                    .hps_io_phery_emac1_RX_CLK
		input  wire        sys_hps_io_hps_io_phery_emac1_RXD0,   //                    .hps_io_phery_emac1_RXD0
		input  wire        sys_hps_io_hps_io_phery_emac1_RXD1,   //                    .hps_io_phery_emac1_RXD1
		input  wire        sys_hps_io_hps_io_phery_emac1_RXD2,   //                    .hps_io_phery_emac1_RXD2
		input  wire        sys_hps_io_hps_io_phery_emac1_RXD3,   //                    .hps_io_phery_emac1_RXD3
		inout  wire        sys_hps_io_hps_io_phery_emac1_MDIO,   //                    .hps_io_phery_emac1_MDIO
		output wire        sys_hps_io_hps_io_phery_emac1_MDC,    //                    .hps_io_phery_emac1_MDC
		inout  wire        sys_hps_io_hps_io_phery_sdmmc_CMD,    //                    .hps_io_phery_sdmmc_CMD
		inout  wire        sys_hps_io_hps_io_phery_sdmmc_D0,     //                    .hps_io_phery_sdmmc_D0
		inout  wire        sys_hps_io_hps_io_phery_sdmmc_D1,     //                    .hps_io_phery_sdmmc_D1
		inout  wire        sys_hps_io_hps_io_phery_sdmmc_D2,     //                    .hps_io_phery_sdmmc_D2
		inout  wire        sys_hps_io_hps_io_phery_sdmmc_D3,     //                    .hps_io_phery_sdmmc_D3
		output wire        sys_hps_io_hps_io_phery_sdmmc_CCLK,   //                    .hps_io_phery_sdmmc_CCLK
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA0,   //                    .hps_io_phery_usb1_DATA0
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA1,   //                    .hps_io_phery_usb1_DATA1
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA2,   //                    .hps_io_phery_usb1_DATA2
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA3,   //                    .hps_io_phery_usb1_DATA3
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA4,   //                    .hps_io_phery_usb1_DATA4
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA5,   //                    .hps_io_phery_usb1_DATA5
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA6,   //                    .hps_io_phery_usb1_DATA6
		inout  wire        sys_hps_io_hps_io_phery_usb1_DATA7,   //                    .hps_io_phery_usb1_DATA7
		input  wire        sys_hps_io_hps_io_phery_usb1_CLK,     //                    .hps_io_phery_usb1_CLK
		output wire        sys_hps_io_hps_io_phery_usb1_STP,     //                    .hps_io_phery_usb1_STP
		input  wire        sys_hps_io_hps_io_phery_usb1_DIR,     //                    .hps_io_phery_usb1_DIR
		input  wire        sys_hps_io_hps_io_phery_usb1_NXT,     //                    .hps_io_phery_usb1_NXT
		input  wire        sys_hps_io_hps_io_phery_uart1_RX,     //                    .hps_io_phery_uart1_RX
		output wire        sys_hps_io_hps_io_phery_uart1_TX,     //                    .hps_io_phery_uart1_TX
		inout  wire        sys_hps_io_hps_io_phery_i2c1_SDA,     //                    .hps_io_phery_i2c1_SDA
		inout  wire        sys_hps_io_hps_io_phery_i2c1_SCL,     //                    .hps_io_phery_i2c1_SCL
		inout  wire        sys_hps_io_hps_io_gpio_gpio0_io1,     //                    .hps_io_gpio_gpio0_io1
		inout  wire        sys_hps_io_hps_io_gpio_gpio0_io9,     //                    .hps_io_gpio_gpio0_io9
		output wire        sys_hps_out_rstn_reset_n,             //    sys_hps_out_rstn.reset_n
		input  wire        sys_rstn_reset_n                      //            sys_rstn.reset_n
	);

	wire     [1:0] sys_hps_emif_gp_to_emif;                             // sys_hps:emif_gp_to_emif -> sys_hps_ddr4_cntrl:hps_to_emif_gp
	wire  [4095:0] sys_hps_ddr4_cntrl_hps_emif_conduit_end_emif_to_hps; // sys_hps_ddr4_cntrl:emif_to_hps -> sys_hps:emif_emif_to_hps
	wire     [0:0] sys_hps_ddr4_cntrl_hps_emif_conduit_end_emif_to_gp;  // sys_hps_ddr4_cntrl:emif_to_hps_gp -> sys_hps:emif_emif_to_gp
	wire  [4095:0] sys_hps_emif_hps_to_emif;                            // sys_hps:emif_hps_to_emif -> sys_hps_ddr4_cntrl:hps_to_emif
	wire    [31:0] sys_hps_f2h_irq0_irq;                                // irq_mapper:sender_irq -> sys_hps:f2h_irq_p0
	wire    [31:0] sys_hps_f2h_irq1_irq;                                // irq_mapper_001:sender_irq -> sys_hps:f2h_irq_p1
	wire           rst_controller_reset_out_reset;                      // rst_controller:reset_out -> sys_hps:h2f_lw_axi_rst

	system_bd_altera_arria10_hps_180_sja5gji #(
		.F2S_Width (0),
		.S2F_Width (0)
	) sys_hps (
		.h2f_rst_n                 (sys_hps_out_rstn_reset_n),                            //         h2f_reset.reset_n
		.s2f_user0_clk             (),                                                    //   h2f_user0_clock.clk
		.emif_emif_to_hps          (sys_hps_ddr4_cntrl_hps_emif_conduit_end_emif_to_hps), //              emif.emif_to_hps
		.emif_hps_to_emif          (sys_hps_emif_hps_to_emif),                            //                  .hps_to_emif
		.emif_emif_to_gp           (sys_hps_ddr4_cntrl_hps_emif_conduit_end_emif_to_gp),  //                  .emif_to_gp
		.emif_gp_to_emif           (sys_hps_emif_gp_to_emif),                             //                  .gp_to_emif
		.h2f_lw_axi_clk            (sys_clk_clk),                                         //  h2f_lw_axi_clock.clk
		.h2f_lw_axi_rst            (~rst_controller_reset_out_reset),                     //  h2f_lw_axi_reset.reset_n
		.h2f_lw_AWID               (),                                                    // h2f_lw_axi_master.awid
		.h2f_lw_AWADDR             (),                                                    //                  .awaddr
		.h2f_lw_AWLEN              (),                                                    //                  .awlen
		.h2f_lw_AWSIZE             (),                                                    //                  .awsize
		.h2f_lw_AWBURST            (),                                                    //                  .awburst
		.h2f_lw_AWLOCK             (),                                                    //                  .awlock
		.h2f_lw_AWCACHE            (),                                                    //                  .awcache
		.h2f_lw_AWPROT             (),                                                    //                  .awprot
		.h2f_lw_AWVALID            (),                                                    //                  .awvalid
		.h2f_lw_AWREADY            (),                                                    //                  .awready
		.h2f_lw_AWUSER             (),                                                    //                  .awuser
		.h2f_lw_WID                (),                                                    //                  .wid
		.h2f_lw_WDATA              (),                                                    //                  .wdata
		.h2f_lw_WSTRB              (),                                                    //                  .wstrb
		.h2f_lw_WLAST              (),                                                    //                  .wlast
		.h2f_lw_WVALID             (),                                                    //                  .wvalid
		.h2f_lw_WREADY             (),                                                    //                  .wready
		.h2f_lw_BID                (),                                                    //                  .bid
		.h2f_lw_BRESP              (),                                                    //                  .bresp
		.h2f_lw_BVALID             (),                                                    //                  .bvalid
		.h2f_lw_BREADY             (),                                                    //                  .bready
		.h2f_lw_ARID               (),                                                    //                  .arid
		.h2f_lw_ARADDR             (),                                                    //                  .araddr
		.h2f_lw_ARLEN              (),                                                    //                  .arlen
		.h2f_lw_ARSIZE             (),                                                    //                  .arsize
		.h2f_lw_ARBURST            (),                                                    //                  .arburst
		.h2f_lw_ARLOCK             (),                                                    //                  .arlock
		.h2f_lw_ARCACHE            (),                                                    //                  .arcache
		.h2f_lw_ARPROT             (),                                                    //                  .arprot
		.h2f_lw_ARVALID            (),                                                    //                  .arvalid
		.h2f_lw_ARREADY            (),                                                    //                  .arready
		.h2f_lw_ARUSER             (),                                                    //                  .aruser
		.h2f_lw_RID                (),                                                    //                  .rid
		.h2f_lw_RDATA              (),                                                    //                  .rdata
		.h2f_lw_RRESP              (),                                                    //                  .rresp
		.h2f_lw_RLAST              (),                                                    //                  .rlast
		.h2f_lw_RVALID             (),                                                    //                  .rvalid
		.h2f_lw_RREADY             (),                                                    //                  .rready
		.f2h_irq_p0                (sys_hps_f2h_irq0_irq),                                //          f2h_irq0.irq
		.f2h_irq_p1                (sys_hps_f2h_irq1_irq),                                //          f2h_irq1.irq
		.hps_io_phery_emac1_TX_CLK (sys_hps_io_hps_io_phery_emac1_TX_CLK),                //            hps_io.hps_io_phery_emac1_TX_CLK
		.hps_io_phery_emac1_TXD0   (sys_hps_io_hps_io_phery_emac1_TXD0),                  //                  .hps_io_phery_emac1_TXD0
		.hps_io_phery_emac1_TXD1   (sys_hps_io_hps_io_phery_emac1_TXD1),                  //                  .hps_io_phery_emac1_TXD1
		.hps_io_phery_emac1_TXD2   (sys_hps_io_hps_io_phery_emac1_TXD2),                  //                  .hps_io_phery_emac1_TXD2
		.hps_io_phery_emac1_TXD3   (sys_hps_io_hps_io_phery_emac1_TXD3),                  //                  .hps_io_phery_emac1_TXD3
		.hps_io_phery_emac1_RX_CTL (sys_hps_io_hps_io_phery_emac1_RX_CTL),                //                  .hps_io_phery_emac1_RX_CTL
		.hps_io_phery_emac1_TX_CTL (sys_hps_io_hps_io_phery_emac1_TX_CTL),                //                  .hps_io_phery_emac1_TX_CTL
		.hps_io_phery_emac1_RX_CLK (sys_hps_io_hps_io_phery_emac1_RX_CLK),                //                  .hps_io_phery_emac1_RX_CLK
		.hps_io_phery_emac1_RXD0   (sys_hps_io_hps_io_phery_emac1_RXD0),                  //                  .hps_io_phery_emac1_RXD0
		.hps_io_phery_emac1_RXD1   (sys_hps_io_hps_io_phery_emac1_RXD1),                  //                  .hps_io_phery_emac1_RXD1
		.hps_io_phery_emac1_RXD2   (sys_hps_io_hps_io_phery_emac1_RXD2),                  //                  .hps_io_phery_emac1_RXD2
		.hps_io_phery_emac1_RXD3   (sys_hps_io_hps_io_phery_emac1_RXD3),                  //                  .hps_io_phery_emac1_RXD3
		.hps_io_phery_emac1_MDIO   (sys_hps_io_hps_io_phery_emac1_MDIO),                  //                  .hps_io_phery_emac1_MDIO
		.hps_io_phery_emac1_MDC    (sys_hps_io_hps_io_phery_emac1_MDC),                   //                  .hps_io_phery_emac1_MDC
		.hps_io_phery_sdmmc_CMD    (sys_hps_io_hps_io_phery_sdmmc_CMD),                   //                  .hps_io_phery_sdmmc_CMD
		.hps_io_phery_sdmmc_D0     (sys_hps_io_hps_io_phery_sdmmc_D0),                    //                  .hps_io_phery_sdmmc_D0
		.hps_io_phery_sdmmc_D1     (sys_hps_io_hps_io_phery_sdmmc_D1),                    //                  .hps_io_phery_sdmmc_D1
		.hps_io_phery_sdmmc_D2     (sys_hps_io_hps_io_phery_sdmmc_D2),                    //                  .hps_io_phery_sdmmc_D2
		.hps_io_phery_sdmmc_D3     (sys_hps_io_hps_io_phery_sdmmc_D3),                    //                  .hps_io_phery_sdmmc_D3
		.hps_io_phery_sdmmc_CCLK   (sys_hps_io_hps_io_phery_sdmmc_CCLK),                  //                  .hps_io_phery_sdmmc_CCLK
		.hps_io_phery_usb1_DATA0   (sys_hps_io_hps_io_phery_usb1_DATA0),                  //                  .hps_io_phery_usb1_DATA0
		.hps_io_phery_usb1_DATA1   (sys_hps_io_hps_io_phery_usb1_DATA1),                  //                  .hps_io_phery_usb1_DATA1
		.hps_io_phery_usb1_DATA2   (sys_hps_io_hps_io_phery_usb1_DATA2),                  //                  .hps_io_phery_usb1_DATA2
		.hps_io_phery_usb1_DATA3   (sys_hps_io_hps_io_phery_usb1_DATA3),                  //                  .hps_io_phery_usb1_DATA3
		.hps_io_phery_usb1_DATA4   (sys_hps_io_hps_io_phery_usb1_DATA4),                  //                  .hps_io_phery_usb1_DATA4
		.hps_io_phery_usb1_DATA5   (sys_hps_io_hps_io_phery_usb1_DATA5),                  //                  .hps_io_phery_usb1_DATA5
		.hps_io_phery_usb1_DATA6   (sys_hps_io_hps_io_phery_usb1_DATA6),                  //                  .hps_io_phery_usb1_DATA6
		.hps_io_phery_usb1_DATA7   (sys_hps_io_hps_io_phery_usb1_DATA7),                  //                  .hps_io_phery_usb1_DATA7
		.hps_io_phery_usb1_CLK     (sys_hps_io_hps_io_phery_usb1_CLK),                    //                  .hps_io_phery_usb1_CLK
		.hps_io_phery_usb1_STP     (sys_hps_io_hps_io_phery_usb1_STP),                    //                  .hps_io_phery_usb1_STP
		.hps_io_phery_usb1_DIR     (sys_hps_io_hps_io_phery_usb1_DIR),                    //                  .hps_io_phery_usb1_DIR
		.hps_io_phery_usb1_NXT     (sys_hps_io_hps_io_phery_usb1_NXT),                    //                  .hps_io_phery_usb1_NXT
		.hps_io_phery_uart1_RX     (sys_hps_io_hps_io_phery_uart1_RX),                    //                  .hps_io_phery_uart1_RX
		.hps_io_phery_uart1_TX     (sys_hps_io_hps_io_phery_uart1_TX),                    //                  .hps_io_phery_uart1_TX
		.hps_io_phery_i2c1_SDA     (sys_hps_io_hps_io_phery_i2c1_SDA),                    //                  .hps_io_phery_i2c1_SDA
		.hps_io_phery_i2c1_SCL     (sys_hps_io_hps_io_phery_i2c1_SCL),                    //                  .hps_io_phery_i2c1_SCL
		.hps_io_gpio_gpio0_io1     (sys_hps_io_hps_io_gpio_gpio0_io1),                    //                  .hps_io_gpio_gpio0_io1
		.hps_io_gpio_gpio0_io9     (sys_hps_io_hps_io_gpio_gpio0_io9)                     //                  .hps_io_gpio_gpio0_io9
	);

	system_bd_altera_emif_a10_hps_180_ebac5ai sys_hps_ddr4_cntrl (
		.global_reset_n (sys_hps_ddr_rstn_reset_n),                            // global_reset_reset_sink.reset_n
		.pll_ref_clk    (sys_hps_ddr_ref_clk_clk),                             //  pll_ref_clk_clock_sink.clk
		.oct_rzqin      (sys_hps_ddr_oct_oct_rzqin),                           //         oct_conduit_end.oct_rzqin
		.mem_ck         (sys_hps_ddr_mem_ck),                                  //         mem_conduit_end.mem_ck
		.mem_ck_n       (sys_hps_ddr_mem_ck_n),                                //                        .mem_ck_n
		.mem_a          (sys_hps_ddr_mem_a),                                   //                        .mem_a
		.mem_act_n      (sys_hps_ddr_mem_act_n),                               //                        .mem_act_n
		.mem_ba         (sys_hps_ddr_mem_ba),                                  //                        .mem_ba
		.mem_bg         (sys_hps_ddr_mem_bg),                                  //                        .mem_bg
		.mem_cke        (sys_hps_ddr_mem_cke),                                 //                        .mem_cke
		.mem_cs_n       (sys_hps_ddr_mem_cs_n),                                //                        .mem_cs_n
		.mem_odt        (sys_hps_ddr_mem_odt),                                 //                        .mem_odt
		.mem_reset_n    (sys_hps_ddr_mem_reset_n),                             //                        .mem_reset_n
		.mem_par        (sys_hps_ddr_mem_par),                                 //                        .mem_par
		.mem_alert_n    (sys_hps_ddr_mem_alert_n),                             //                        .mem_alert_n
		.mem_dqs        (sys_hps_ddr_mem_dqs),                                 //                        .mem_dqs
		.mem_dqs_n      (sys_hps_ddr_mem_dqs_n),                               //                        .mem_dqs_n
		.mem_dq         (sys_hps_ddr_mem_dq),                                  //                        .mem_dq
		.mem_dbi_n      (sys_hps_ddr_mem_dbi_n),                               //                        .mem_dbi_n
		.hps_to_emif    (sys_hps_emif_hps_to_emif),                            //    hps_emif_conduit_end.hps_to_emif
		.emif_to_hps    (sys_hps_ddr4_cntrl_hps_emif_conduit_end_emif_to_hps), //                        .emif_to_hps
		.hps_to_emif_gp (sys_hps_emif_gp_to_emif),                             //                        .gp_to_emif
		.emif_to_hps_gp (sys_hps_ddr4_cntrl_hps_emif_conduit_end_emif_to_gp)   //                        .emif_to_gp
	);

	system_bd_altera_irq_mapper_180_vrecy4a irq_mapper (
		.clk        (),                     //       clk.clk
		.reset      (),                     // clk_reset.reset
		.sender_irq (sys_hps_f2h_irq0_irq)  //    sender.irq
	);

	system_bd_altera_irq_mapper_180_vrecy4a irq_mapper_001 (
		.clk        (),                     //       clk.clk
		.reset      (),                     // clk_reset.reset
		.sender_irq (sys_hps_f2h_irq1_irq)  //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~sys_rstn_reset_n),              // reset_in0.reset
		.clk            (sys_clk_clk),                    //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
