	system_bd u0 (
		.sys_clk_clk                          (<connected-to-sys_clk_clk>),                          //             sys_clk.clk
		.sys_hps_ddr_mem_ck                   (<connected-to-sys_hps_ddr_mem_ck>),                   //         sys_hps_ddr.mem_ck
		.sys_hps_ddr_mem_ck_n                 (<connected-to-sys_hps_ddr_mem_ck_n>),                 //                    .mem_ck_n
		.sys_hps_ddr_mem_a                    (<connected-to-sys_hps_ddr_mem_a>),                    //                    .mem_a
		.sys_hps_ddr_mem_act_n                (<connected-to-sys_hps_ddr_mem_act_n>),                //                    .mem_act_n
		.sys_hps_ddr_mem_ba                   (<connected-to-sys_hps_ddr_mem_ba>),                   //                    .mem_ba
		.sys_hps_ddr_mem_bg                   (<connected-to-sys_hps_ddr_mem_bg>),                   //                    .mem_bg
		.sys_hps_ddr_mem_cke                  (<connected-to-sys_hps_ddr_mem_cke>),                  //                    .mem_cke
		.sys_hps_ddr_mem_cs_n                 (<connected-to-sys_hps_ddr_mem_cs_n>),                 //                    .mem_cs_n
		.sys_hps_ddr_mem_odt                  (<connected-to-sys_hps_ddr_mem_odt>),                  //                    .mem_odt
		.sys_hps_ddr_mem_reset_n              (<connected-to-sys_hps_ddr_mem_reset_n>),              //                    .mem_reset_n
		.sys_hps_ddr_mem_par                  (<connected-to-sys_hps_ddr_mem_par>),                  //                    .mem_par
		.sys_hps_ddr_mem_alert_n              (<connected-to-sys_hps_ddr_mem_alert_n>),              //                    .mem_alert_n
		.sys_hps_ddr_mem_dqs                  (<connected-to-sys_hps_ddr_mem_dqs>),                  //                    .mem_dqs
		.sys_hps_ddr_mem_dqs_n                (<connected-to-sys_hps_ddr_mem_dqs_n>),                //                    .mem_dqs_n
		.sys_hps_ddr_mem_dq                   (<connected-to-sys_hps_ddr_mem_dq>),                   //                    .mem_dq
		.sys_hps_ddr_mem_dbi_n                (<connected-to-sys_hps_ddr_mem_dbi_n>),                //                    .mem_dbi_n
		.sys_hps_ddr_oct_oct_rzqin            (<connected-to-sys_hps_ddr_oct_oct_rzqin>),            //     sys_hps_ddr_oct.oct_rzqin
		.sys_hps_ddr_ref_clk_clk              (<connected-to-sys_hps_ddr_ref_clk_clk>),              // sys_hps_ddr_ref_clk.clk
		.sys_hps_ddr_rstn_reset_n             (<connected-to-sys_hps_ddr_rstn_reset_n>),             //    sys_hps_ddr_rstn.reset_n
		.sys_hps_io_hps_io_phery_emac1_TX_CLK (<connected-to-sys_hps_io_hps_io_phery_emac1_TX_CLK>), //          sys_hps_io.hps_io_phery_emac1_TX_CLK
		.sys_hps_io_hps_io_phery_emac1_TXD0   (<connected-to-sys_hps_io_hps_io_phery_emac1_TXD0>),   //                    .hps_io_phery_emac1_TXD0
		.sys_hps_io_hps_io_phery_emac1_TXD1   (<connected-to-sys_hps_io_hps_io_phery_emac1_TXD1>),   //                    .hps_io_phery_emac1_TXD1
		.sys_hps_io_hps_io_phery_emac1_TXD2   (<connected-to-sys_hps_io_hps_io_phery_emac1_TXD2>),   //                    .hps_io_phery_emac1_TXD2
		.sys_hps_io_hps_io_phery_emac1_TXD3   (<connected-to-sys_hps_io_hps_io_phery_emac1_TXD3>),   //                    .hps_io_phery_emac1_TXD3
		.sys_hps_io_hps_io_phery_emac1_RX_CTL (<connected-to-sys_hps_io_hps_io_phery_emac1_RX_CTL>), //                    .hps_io_phery_emac1_RX_CTL
		.sys_hps_io_hps_io_phery_emac1_TX_CTL (<connected-to-sys_hps_io_hps_io_phery_emac1_TX_CTL>), //                    .hps_io_phery_emac1_TX_CTL
		.sys_hps_io_hps_io_phery_emac1_RX_CLK (<connected-to-sys_hps_io_hps_io_phery_emac1_RX_CLK>), //                    .hps_io_phery_emac1_RX_CLK
		.sys_hps_io_hps_io_phery_emac1_RXD0   (<connected-to-sys_hps_io_hps_io_phery_emac1_RXD0>),   //                    .hps_io_phery_emac1_RXD0
		.sys_hps_io_hps_io_phery_emac1_RXD1   (<connected-to-sys_hps_io_hps_io_phery_emac1_RXD1>),   //                    .hps_io_phery_emac1_RXD1
		.sys_hps_io_hps_io_phery_emac1_RXD2   (<connected-to-sys_hps_io_hps_io_phery_emac1_RXD2>),   //                    .hps_io_phery_emac1_RXD2
		.sys_hps_io_hps_io_phery_emac1_RXD3   (<connected-to-sys_hps_io_hps_io_phery_emac1_RXD3>),   //                    .hps_io_phery_emac1_RXD3
		.sys_hps_io_hps_io_phery_emac1_MDIO   (<connected-to-sys_hps_io_hps_io_phery_emac1_MDIO>),   //                    .hps_io_phery_emac1_MDIO
		.sys_hps_io_hps_io_phery_emac1_MDC    (<connected-to-sys_hps_io_hps_io_phery_emac1_MDC>),    //                    .hps_io_phery_emac1_MDC
		.sys_hps_io_hps_io_phery_sdmmc_CMD    (<connected-to-sys_hps_io_hps_io_phery_sdmmc_CMD>),    //                    .hps_io_phery_sdmmc_CMD
		.sys_hps_io_hps_io_phery_sdmmc_D0     (<connected-to-sys_hps_io_hps_io_phery_sdmmc_D0>),     //                    .hps_io_phery_sdmmc_D0
		.sys_hps_io_hps_io_phery_sdmmc_D1     (<connected-to-sys_hps_io_hps_io_phery_sdmmc_D1>),     //                    .hps_io_phery_sdmmc_D1
		.sys_hps_io_hps_io_phery_sdmmc_D2     (<connected-to-sys_hps_io_hps_io_phery_sdmmc_D2>),     //                    .hps_io_phery_sdmmc_D2
		.sys_hps_io_hps_io_phery_sdmmc_D3     (<connected-to-sys_hps_io_hps_io_phery_sdmmc_D3>),     //                    .hps_io_phery_sdmmc_D3
		.sys_hps_io_hps_io_phery_sdmmc_CCLK   (<connected-to-sys_hps_io_hps_io_phery_sdmmc_CCLK>),   //                    .hps_io_phery_sdmmc_CCLK
		.sys_hps_io_hps_io_phery_usb1_DATA0   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA0>),   //                    .hps_io_phery_usb1_DATA0
		.sys_hps_io_hps_io_phery_usb1_DATA1   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA1>),   //                    .hps_io_phery_usb1_DATA1
		.sys_hps_io_hps_io_phery_usb1_DATA2   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA2>),   //                    .hps_io_phery_usb1_DATA2
		.sys_hps_io_hps_io_phery_usb1_DATA3   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA3>),   //                    .hps_io_phery_usb1_DATA3
		.sys_hps_io_hps_io_phery_usb1_DATA4   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA4>),   //                    .hps_io_phery_usb1_DATA4
		.sys_hps_io_hps_io_phery_usb1_DATA5   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA5>),   //                    .hps_io_phery_usb1_DATA5
		.sys_hps_io_hps_io_phery_usb1_DATA6   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA6>),   //                    .hps_io_phery_usb1_DATA6
		.sys_hps_io_hps_io_phery_usb1_DATA7   (<connected-to-sys_hps_io_hps_io_phery_usb1_DATA7>),   //                    .hps_io_phery_usb1_DATA7
		.sys_hps_io_hps_io_phery_usb1_CLK     (<connected-to-sys_hps_io_hps_io_phery_usb1_CLK>),     //                    .hps_io_phery_usb1_CLK
		.sys_hps_io_hps_io_phery_usb1_STP     (<connected-to-sys_hps_io_hps_io_phery_usb1_STP>),     //                    .hps_io_phery_usb1_STP
		.sys_hps_io_hps_io_phery_usb1_DIR     (<connected-to-sys_hps_io_hps_io_phery_usb1_DIR>),     //                    .hps_io_phery_usb1_DIR
		.sys_hps_io_hps_io_phery_usb1_NXT     (<connected-to-sys_hps_io_hps_io_phery_usb1_NXT>),     //                    .hps_io_phery_usb1_NXT
		.sys_hps_io_hps_io_phery_uart1_RX     (<connected-to-sys_hps_io_hps_io_phery_uart1_RX>),     //                    .hps_io_phery_uart1_RX
		.sys_hps_io_hps_io_phery_uart1_TX     (<connected-to-sys_hps_io_hps_io_phery_uart1_TX>),     //                    .hps_io_phery_uart1_TX
		.sys_hps_io_hps_io_phery_i2c1_SDA     (<connected-to-sys_hps_io_hps_io_phery_i2c1_SDA>),     //                    .hps_io_phery_i2c1_SDA
		.sys_hps_io_hps_io_phery_i2c1_SCL     (<connected-to-sys_hps_io_hps_io_phery_i2c1_SCL>),     //                    .hps_io_phery_i2c1_SCL
		.sys_hps_io_hps_io_gpio_gpio0_io1     (<connected-to-sys_hps_io_hps_io_gpio_gpio0_io1>),     //                    .hps_io_gpio_gpio0_io1
		.sys_hps_io_hps_io_gpio_gpio0_io9     (<connected-to-sys_hps_io_hps_io_gpio_gpio0_io9>),     //                    .hps_io_gpio_gpio0_io9
		.sys_hps_out_rstn_reset_n             (<connected-to-sys_hps_out_rstn_reset_n>),             //    sys_hps_out_rstn.reset_n
		.sys_rstn_reset_n                     (<connected-to-sys_rstn_reset_n>)                      //            sys_rstn.reset_n
	);

